/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Vista Soft IT
 */
public class MainWindow extends javax.swing.JFrame {
    
    private int plus=1;
    private int minus=2;
    private int div=3;
    private int multi=4;
    private int mod=5;
    
    private int operatorControlar=0;
    
    private float firstValue=-1;
    private float secondValue=-1;
    private float result=0;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelShowResult = new javax.swing.JLabel();
        jLabelCalculatorConsol = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jButtonSingleClear = new javax.swing.JButton();
        jButtonMod = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonSum = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonSubstract = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonMultiplay = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonNum0 = new javax.swing.JButton();
        jButtonDevisor = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jTextCalculatorConsolResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 150));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("PRX BC-V001");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelShowResult.setForeground(new java.awt.Color(204, 0, 0));
        jLabelShowResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelShowResult.setText("0");

        jLabelCalculatorConsol.setBackground(new java.awt.Color(255, 255, 255));
        jLabelCalculatorConsol.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCalculatorConsol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jLabelCalculatorConsol.setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("<-");
        jButton1.setToolTipText("");
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonClearAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonClearAll.setText("CE");
        jButtonClearAll.setToolTipText("");
        jButtonClearAll.setBorderPainted(false);
        jButtonClearAll.setDefaultCapable(false);
        jButtonClearAll.setFocusPainted(false);
        jButtonClearAll.setFocusable(false);
        jButtonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllActionPerformed(evt);
            }
        });

        jButtonSingleClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSingleClear.setText("C");
        jButtonSingleClear.setToolTipText("");
        jButtonSingleClear.setBorderPainted(false);
        jButtonSingleClear.setDefaultCapable(false);
        jButtonSingleClear.setFocusPainted(false);
        jButtonSingleClear.setFocusable(false);
        jButtonSingleClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSingleClearActionPerformed(evt);
            }
        });

        jButtonMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMod.setText("Mod");
        jButtonMod.setToolTipText("");
        jButtonMod.setBorderPainted(false);
        jButtonMod.setDefaultCapable(false);
        jButtonMod.setFocusPainted(false);
        jButtonMod.setFocusable(false);
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jButtonNum1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum1.setText("1");
        jButtonNum1.setToolTipText("");
        jButtonNum1.setBorderPainted(false);
        jButtonNum1.setDefaultCapable(false);
        jButtonNum1.setFocusPainted(false);
        jButtonNum1.setFocusable(false);
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });

        jButtonNum2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum2.setText("2");
        jButtonNum2.setToolTipText("");
        jButtonNum2.setBorderPainted(false);
        jButtonNum2.setDefaultCapable(false);
        jButtonNum2.setFocusPainted(false);
        jButtonNum2.setFocusable(false);
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });

        jButtonNum3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum3.setText("3");
        jButtonNum3.setToolTipText("");
        jButtonNum3.setBorderPainted(false);
        jButtonNum3.setDefaultCapable(false);
        jButtonNum3.setFocusPainted(false);
        jButtonNum3.setFocusable(false);
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });

        jButtonSum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSum.setText("+");
        jButtonSum.setToolTipText("");
        jButtonSum.setBorderPainted(false);
        jButtonSum.setDefaultCapable(false);
        jButtonSum.setFocusPainted(false);
        jButtonSum.setFocusable(false);
        jButtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumActionPerformed(evt);
            }
        });

        jButtonNum4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum4.setText("4");
        jButtonNum4.setToolTipText("");
        jButtonNum4.setBorderPainted(false);
        jButtonNum4.setDefaultCapable(false);
        jButtonNum4.setFocusPainted(false);
        jButtonNum4.setFocusable(false);
        jButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum4ActionPerformed(evt);
            }
        });

        jButtonNum5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum5.setText("5");
        jButtonNum5.setToolTipText("");
        jButtonNum5.setBorderPainted(false);
        jButtonNum5.setDefaultCapable(false);
        jButtonNum5.setFocusPainted(false);
        jButtonNum5.setFocusable(false);
        jButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum5ActionPerformed(evt);
            }
        });

        jButtonNum6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum6.setText("6");
        jButtonNum6.setToolTipText("");
        jButtonNum6.setBorderPainted(false);
        jButtonNum6.setDefaultCapable(false);
        jButtonNum6.setFocusPainted(false);
        jButtonNum6.setFocusable(false);
        jButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum6ActionPerformed(evt);
            }
        });

        jButtonSubstract.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSubstract.setText("-");
        jButtonSubstract.setToolTipText("");
        jButtonSubstract.setBorderPainted(false);
        jButtonSubstract.setDefaultCapable(false);
        jButtonSubstract.setFocusPainted(false);
        jButtonSubstract.setFocusable(false);
        jButtonSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractActionPerformed(evt);
            }
        });

        jButtonNum7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum7.setText("7");
        jButtonNum7.setToolTipText("");
        jButtonNum7.setBorderPainted(false);
        jButtonNum7.setDefaultCapable(false);
        jButtonNum7.setFocusPainted(false);
        jButtonNum7.setFocusable(false);
        jButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum7ActionPerformed(evt);
            }
        });

        jButtonNum8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum8.setText("8");
        jButtonNum8.setToolTipText("");
        jButtonNum8.setBorderPainted(false);
        jButtonNum8.setDefaultCapable(false);
        jButtonNum8.setFocusPainted(false);
        jButtonNum8.setFocusable(false);
        jButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum8ActionPerformed(evt);
            }
        });

        jButtonMultiplay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonMultiplay.setText("*");
        jButtonMultiplay.setToolTipText("");
        jButtonMultiplay.setBorderPainted(false);
        jButtonMultiplay.setDefaultCapable(false);
        jButtonMultiplay.setFocusPainted(false);
        jButtonMultiplay.setFocusable(false);
        jButtonMultiplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplayActionPerformed(evt);
            }
        });

        jButtonNum9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum9.setText("9");
        jButtonNum9.setToolTipText("");
        jButtonNum9.setBorderPainted(false);
        jButtonNum9.setDefaultCapable(false);
        jButtonNum9.setFocusPainted(false);
        jButtonNum9.setFocusable(false);
        jButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum9ActionPerformed(evt);
            }
        });

        jButtonNum0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonNum0.setText("0");
        jButtonNum0.setToolTipText("");
        jButtonNum0.setBorderPainted(false);
        jButtonNum0.setDefaultCapable(false);
        jButtonNum0.setFocusPainted(false);
        jButtonNum0.setFocusable(false);
        jButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum0ActionPerformed(evt);
            }
        });

        jButtonDevisor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDevisor.setText("/");
        jButtonDevisor.setToolTipText("");
        jButtonDevisor.setBorderPainted(false);
        jButtonDevisor.setDefaultCapable(false);
        jButtonDevisor.setFocusPainted(false);
        jButtonDevisor.setFocusable(false);
        jButtonDevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDevisorActionPerformed(evt);
            }
        });

        jButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.setToolTipText("");
        jButtonEqual.setBorderPainted(false);
        jButtonEqual.setDefaultCapable(false);
        jButtonEqual.setFocusPainted(false);
        jButtonEqual.setFocusable(false);
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonNum0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNum4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNum7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNum2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNum5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNum8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDevisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNum9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSingleClear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNum6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSubstract, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMultiplay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonClearAll)
                    .addComponent(jButtonSingleClear)
                    .addComponent(jButtonMod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextCalculatorConsolResult.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextCalculatorConsolResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        jTextCalculatorConsolResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCalculatorConsolResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelShowResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCalculatorConsolResult, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCalculatorConsol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelCalculatorConsol, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelShowResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCalculatorConsolResult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"1");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"1");
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"2");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"2");
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"3");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"3");
    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumActionPerformed
        // TODO add your handling code here:
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            
            firstValue=result;
            jTextCalculatorConsolResult.setText("");
            secondValue=-1;
        }
        operatorControlar=plus;
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"+");
    }//GEN-LAST:event_jButtonSumActionPerformed

    private void jButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum4ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"4");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"4");
    }//GEN-LAST:event_jButtonNum4ActionPerformed

    private void jButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum5ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"5");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"5");
    }//GEN-LAST:event_jButtonNum5ActionPerformed

    private void jButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum6ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"6");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"6");
    }//GEN-LAST:event_jButtonNum6ActionPerformed

    private void jButtonSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractActionPerformed
        // TODO add your handling code here:
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            
            firstValue=result;
            jTextCalculatorConsolResult.setText("");
            secondValue=-1;
        }
        operatorControlar=minus;
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"-");
    }//GEN-LAST:event_jButtonSubstractActionPerformed

    private void jButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum7ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"7");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"7");
    }//GEN-LAST:event_jButtonNum7ActionPerformed

    private void jButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum8ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"8");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"8");
    }//GEN-LAST:event_jButtonNum8ActionPerformed

    private void jButtonMultiplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplayActionPerformed
        // TODO add your handling code here:
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            
            firstValue=result;
            jTextCalculatorConsolResult.setText("");
            secondValue=-1;
        }
        operatorControlar=multi;
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"*");
    }//GEN-LAST:event_jButtonMultiplayActionPerformed

    private void jButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum9ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"9");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"9");
    }//GEN-LAST:event_jButtonNum9ActionPerformed

    private void jButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum0ActionPerformed
        // TODO add your handling code here:
        jTextCalculatorConsolResult.setText(jTextCalculatorConsolResult.getText()+"0");
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"0");
    }//GEN-LAST:event_jButtonNum0ActionPerformed

    private void jButtonDevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDevisorActionPerformed
        // TODO add your handling code here:
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            
            firstValue=result;
            jTextCalculatorConsolResult.setText("");
            secondValue=-1;
        }
        operatorControlar=div;
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"/");
    }//GEN-LAST:event_jButtonDevisorActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        
//        String[] parts = jLabelCalculatorConsol.getText().split("\\+");
//        System.out.println(parts[0]);
//        System.out.println(parts[1]);
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            System.out.println(result);
            firstValue=-1;
            secondValue=-1;
            result=0;
            operatorControlar=0;
            jTextCalculatorConsolResult.setText("");
        }
        
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed
        // TODO add your handling code here:
        if(firstValue < 0){
            firstValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("F: "+firstValue);
            jTextCalculatorConsolResult.setText("");
       }else{
            secondValue=Integer.parseInt(jTextCalculatorConsolResult.getText());
            System.out.println("S: "+secondValue);
            jTextCalculatorConsolResult.setText("");
        }
        if(firstValue >= 0 && secondValue >= 0){
            if(operatorControlar==plus){result=firstValue+secondValue;}
            else if(operatorControlar==minus){result=firstValue-secondValue;}
            else if(operatorControlar==multi){result=firstValue*secondValue;}
            else if(operatorControlar==div){result=firstValue/secondValue;}
            else if(operatorControlar==mod){result=firstValue%secondValue;}
            
            jLabelShowResult.setText(Float.toString(result));
            
            firstValue=result;
            jTextCalculatorConsolResult.setText("");
            secondValue=-1;
        }
        operatorControlar=mod;
        jLabelCalculatorConsol.setText(jLabelCalculatorConsol.getText()+"%");

    }//GEN-LAST:event_jButtonModActionPerformed

    private void jButtonSingleClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSingleClearActionPerformed
        // TODO add your handling code here:
        int textLength=jTextCalculatorConsolResult.getText().length();
        jTextCalculatorConsolResult.setText("");
        String tempString=jLabelCalculatorConsol.getText();
        jLabelCalculatorConsol.setText(tempString.substring(0,(tempString.length())-textLength));
        
    }//GEN-LAST:event_jButtonSingleClearActionPerformed

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        // TODO add your handling code here:
            firstValue=-1;
            secondValue=-1;
            result=0;
            operatorControlar=0;
            jTextCalculatorConsolResult.setText("");
            jLabelCalculatorConsol.setText("");
            jLabelShowResult.setText("0");
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String tempString=jTextCalculatorConsolResult.getText();
        int strLength=tempString.length();
        jTextCalculatorConsolResult.setText(tempString.substring(0, strLength-1));
        tempString=jLabelCalculatorConsol.getText();
        strLength=tempString.length();
        jLabelCalculatorConsol.setText(tempString.substring(0,strLength-1));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextCalculatorConsolResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCalculatorConsolResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCalculatorConsolResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDevisor;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JButton jButtonMultiplay;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonSingleClear;
    private javax.swing.JButton jButtonSubstract;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCalculatorConsol;
    private javax.swing.JLabel jLabelShowResult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextCalculatorConsolResult;
    // End of variables declaration//GEN-END:variables
}
